version: '3.4'

services:
  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: src/Product/Product.Api/Dockerfile
    networks:
      specific-network: 
        ipv4_address: 172.21.0.2
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: p@nT12HenT
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      specific-network: 
        ipv4_address: 172.21.0.3
networks:
  specific-network:
   ipam:
      config:
        - subnet: 172.21.0.0/16